version: "3"
services:
    vm:
        container_name: dsm
        image: kroese/virtual-dsm:latest
        environment:
            CPU_CORES: "1"
            DISK_SIZE: "16G"
            RAM_SIZE: "512M"
        devices:
            - /dev/kvm
        cap_add:
            - NET_ADMIN        
        ports:
            - 5000:5000
            - 5001:5001
        volumes:
            - /var/dsm:/storage
        restart: on-failure
        stop_grace_period: 60s
