on:
  push:
    paths-ignore:
      - '**/*.md'
      - '.gitignore'
      - '.dockerignore'
      - '.github/**'
      - '.github/workflows/**'

  pull_request:
    paths-ignore:
      - '**/*.md'
      - '.gitignore'
      - '.dockerignore'
      - '.github/**'
      - '.github/workflows/**'

name: "Test"
permissions: {}

jobs:
  check:
    uses: ./.github/workflows/check.yml
